'use strict';

var extend = require('extend-shallow');
var through = require('through2');
var toc = require('markdown-toc');

module.exports = function(verb) {
  verb.plugin('toc.create', function(options) {
    return through.obj(function(file, enc, next) {
      var opts = extend({}, verb.options, options, file.options);
      if (opts.toc === false) {
        return next(null, file);
      }
      var str = file.contents.toString();
      file.toc = toc(str, opts);
      next(null, file);
    });
  });

  verb.plugin('toc.inject', function(options) {
    return through.obj(function(file, enc, next) {
      var opts = extend({}, verb.options, options, file.options);
      var str = file.contents.toString();

      var tocString = (file.toc && file.toc.content) || '';
      if (tocString === '' || opts.toc === false) {
        str = str.replace(/^#+ TOC/gm, '');
        tocString = '';
      }

      tocString += '\n\n_(Table of contents generated by [verb](https://github.com/verbose/verb))_';

      str = str.split('<!-- toc -->').join(tocString);
      str = str.replace(/\n{2,}/g, '\n\n');
      file.contents = new Buffer(str);
      next(null, file);
    });
  });
};
