'use strict';

var includes = {
  'highlight': [
    '{% if (verb.related && verb.related.highlight) { %}',
    'You might also be interested in [{%= verb.related.highlight %}]({%= pkg(verb.related.highlight, "homepage") %}).',
    '{% } %}',
  ].join('\n'),

  'related-list': [
    '{% if (verb.related && verb.related.list && verb.related.list.length) { %}',
    '{%= verb.related.description || "You might also be interested in these projects:" %} ',
    '{%= related(verb.related.list) %}  ',
    '{% } %}',
  ].join('\n'),

  'install-npm': [
    'Install with [npm](https://www.npmjs.com/):',
    '',
    '```sh',
    '$ npm install {%= name %}{%= ((typeof save !== "undefined" && save === true) ? " --save" : "") %}',
    '```'
  ].join('\n'),

  'install-global': [
    'Install globally with [npm](https://www.npmjs.com/)',
    '',
    '```sh',
    '$ npm install -g {%= name %}',
    '```'
  ].join('\n'),

  'install': [
    'Install with [npm](https://www.npmjs.com/):',
    '',
    '```sh',
    '$ npm install {%= name %}',
    '```'
  ].join('\n'),

  'install-dev': [
    'Install as a `devDependency` with [npm](https://www.npmjs.com/):',
    '',
    '```sh',
    '$ npm install {%= name %} --save-dev',
    '```'
  ].join('\n'),

  'install-bower': [
    'Install with [bower](http://bower.io/)',
    '',
    '```sh',
    '$ bower install {%= name %}{%= save === true ? " --save" : "" %}',
    '```'
  ].join('\n'),

  'upgrading': [
    '**Clear your cache and re-install**',
    '',
    'If you\'re currently running {%= name %} v{%= previous("minor", version) %} or lower, please do the following to clear out old versions of {%= name %}, so that the latest version of {%= name %} will install properly:',
    '',
    '```bash',
    '$ npm cache clean && npm i -g {%= name %}',
    '```',
  ].join('\n'),

  'tests': [
    'Install dev dependencies:',
    '',
    '```sh',
    '$ npm install -d && npm test',
    '```'
  ].join('\n'),

  'generate-docs': [
    'Generate readme and API documentation with [verb][]:',
    '',
    '```sh',
    '$ npm install verb && npm run docs',
    '```',
    '',
    'Or, if [verb][] is installed globally:',
    '',
    '```sh',
    '$ verb',
    '```'
  ].join('\n'),

  'author': [
    '**{%= author.name %}**',
    '',
    '+ [github/{%= author.username %}](https://github.com/{%= author.username %})',
    '+ [twitter/{%= author.twitter %}](http://twitter.com/{%= author.twitter %})'
  ].join('\n'),

  'contributing': 'Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/{%= author.username %}/{%= name %}/issues/new).',

  'footer': '_This file was generated by [{%= runner.name %}]({%= runner.url %}), v{%= runner.version %}, on {%= date() %}._'
};

includes['build-docs'] = includes['generate-docs'];

module.exports = includes;